# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'WhiteBoxDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'CocoaAsyncSocket'
pod 'Masonry'
pod 'IQKeyboardManager'
pod 'JSONModel'
pod 'AFNetworking'
pod 'MLeaksFinder'
  # Pods for WhiteBoxDemo

  target 'WhiteBoxDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WhiteBoxDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
